services:
  Proglab\Components\Components\Atoms\Button:
    class: Proglab\Components\Components\Atoms\Button
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\Molecules\Breadcrumb:
    class: Proglab\Components\Components\Molecules\Breadcrumb
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\Molecules\Alert:
    class: Proglab\Components\Components\Molecules\Alert
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\Organisms\Carousel:
    class: Proglab\Components\Components\Organisms\Carousel
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\Organisms\CarouselDto:
    class: Proglab\Components\Components\Organisms\CarouselDto
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Service\CarouselServiceAbstract:
    class: Proglab\Components\Service\CarouselServiceAbstract
    public: true
    autoconfigure: true
    autowire: true