services:
  Proglab\Components\Components\Button\Button:
    class: Proglab\Components\Components\Button\Button
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\Breadcrumb\Breadcrumb:
    class: Proglab\Components\Components\Breadcrumb\Breadcrumb
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\Alert\Alert:
    class: Proglab\Components\Components\Alert\Alert
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\Carousel\Carousel:
    class: Proglab\Components\Components\Carousel\Carousel
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\CarouselDto\CarouselDto:
    class: Proglab\Components\Components\CarouselDto\CarouselDto
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\CarouselDto\Service\CarouselServiceAbstract:
    class: Proglab\Components\Components\CarouselDto\Service\CarouselServiceAbstract
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\Modal\Modal:
    class: Proglab\Components\Components\Modal\Modal
    public: true
    autoconfigure: true
    autowire: true