services:
  Proglab\Components\Components\Atoms\Button:
    class: Proglab\Components\Components\Atoms\Button
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\Molecules\Breadcrumb:
    class: Proglab\Components\Components\Molecules\Breadcrumb
    public: true
    autoconfigure: true
    autowire: true
  Proglab\Components\Components\Molecules\Alert:
    class: Proglab\Components\Components\Molecules\Alert
    public: true
    autoconfigure: true
    autowire: true